/**
 * Tests for delivery hygiene metrics.
 */
import { describe, it, expect } from "vitest";
import { computeHygiene } from "./hygiene";
import type { RawPR } from "../teamAggregation";
import type { EnrichedIssue } from "./types";

describe("computeHygiene", () => {
  const sprintKeys = new Set(["PROJ-1", "PROJ-2", "PROJ-3", "PROJ-4", "PROJ-5"]);

  it("returns prNoJira refs for PRs with no ticket key", () => {
    const prs: RawPR[] = [
      {
        number: 1,
        title: "PROJ-1 foo",
        repo_full_name: "org/repo1",
        html_url: "",
        state: "open",
        checks_status: null,
        author: "alice",
        created_at: "2026-07-01T10:00:00Z",
      },
      {
        number: 2,
        title: "no ticket here",
        repo_full_name: "org/repo2",
        html_url: "",
        state: "open",
        checks_status: null,
        author: "bob",
        created_at: "2026-07-01T11:00:00Z",
      },
      {
        number: 3,
        title: "[PROJ-3] baz",
        repo_full_name: "org/repo3",
        html_url: "",
        state: "open",
        checks_status: null,
        author: "charlie",
        created_at: "2026-07-01T12:00:00Z",
      },
      {
        number: 4,
        title: "another no ticket",
        repo_full_name: "org/repo4",
        html_url: "",
        state: "merged",
        checks_status: null,
        author: "dave",
        created_at: "2026-06-30T08:00:00Z",
      },
    ];
    const result = computeHygiene([], prs, sprintKeys);
    expect(result.prNoJira).toEqual([
      { kind: "pr", repo: "org/repo2", number: 2 },
      { kind: "pr", repo: "org/repo4", number: 4 },
    ]);
  });

  it("returns jiraNoPR refs for in-progress issues with no linked PRs", () => {
    const issues: EnrichedIssue[] = [
      {
        key: "PROJ-1",
        summary: "foo",
        status: "In Progress",
        statusCategory: "indeterminate",
        assigneeAccountId: "123",
        assigneeName: "Alice",
        epicKey: null,
        epicName: null,
        linkedPRs: [],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: true,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-2",
        summary: "bar",
        status: "In Progress",
        statusCategory: "indeterminate",
        assigneeAccountId: "456",
        assigneeName: "Bob",
        epicKey: null,
        epicName: null,
        linkedPRs: [
          {
            number: 1,
            title: "PROJ-2 bar",
            repo_full_name: "org/repo",
            html_url: "",
            state: "open",
            checks_status: null,
            author: "bob",
            createdAt: null,
            mergedAt: null,
            reviewState: null,
            waitingReview: false,
          },
        ],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-3",
        summary: "baz",
        status: "To Do",
        statusCategory: "new",
        assigneeAccountId: null,
        assigneeName: null,
        epicKey: null,
        epicName: null,
        linkedPRs: [],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: true,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-4",
        summary: "qux",
        status: "In Progress",
        statusCategory: "indeterminate",
        assigneeAccountId: "789",
        assigneeName: "Charlie",
        epicKey: null,
        epicName: null,
        linkedPRs: [],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: true,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
    ];
    const result = computeHygiene(issues, [], sprintKeys);
    expect(result.jiraNoPR).toEqual([
      { kind: "issue", key: "PROJ-1" },
      { kind: "issue", key: "PROJ-4" },
    ]);
  });

  it("returns mergedNotDone refs for issues with merged PR but not done status", () => {
    const issues: EnrichedIssue[] = [
      {
        key: "PROJ-1",
        summary: "foo",
        status: "In Progress",
        statusCategory: "indeterminate",
        assigneeAccountId: "123",
        assigneeName: "Alice",
        epicKey: null,
        epicName: null,
        linkedPRs: [
          {
            number: 1,
            title: "PROJ-1 foo",
            repo_full_name: "org/repo",
            html_url: "",
            state: "merged",
            checks_status: null,
            author: "alice",
            createdAt: null,
            mergedAt: "2026-06-30T12:00:00Z",
            reviewState: null,
            waitingReview: false,
          },
        ],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-2",
        summary: "bar",
        status: "Done",
        statusCategory: "done",
        assigneeAccountId: "456",
        assigneeName: "Bob",
        epicKey: null,
        epicName: null,
        linkedPRs: [
          {
            number: 2,
            title: "PROJ-2 bar",
            repo_full_name: "org/repo",
            html_url: "",
            state: "merged",
            checks_status: null,
            author: "bob",
            createdAt: null,
            mergedAt: "2026-06-29T12:00:00Z",
            reviewState: null,
            waitingReview: false,
          },
        ],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-3",
        summary: "baz",
        status: "In Review",
        statusCategory: "indeterminate",
        assigneeAccountId: "789",
        assigneeName: "Charlie",
        epicKey: null,
        epicName: null,
        linkedPRs: [
          {
            number: 3,
            title: "PROJ-3 baz",
            repo_full_name: "org/repo",
            html_url: "",
            state: "open",
            checks_status: null,
            author: "charlie",
            createdAt: null,
            mergedAt: null,
            reviewState: null,
            waitingReview: false,
          },
        ],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: true,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
    ];
    const result = computeHygiene(issues, [], sprintKeys);
    expect(result.mergedNotDone).toEqual([{ kind: "issue", key: "PROJ-1" }]);
  });

  it("returns doneNoMerged refs for done issues with no merged PR", () => {
    const issues: EnrichedIssue[] = [
      {
        key: "PROJ-1",
        summary: "foo",
        status: "Done",
        statusCategory: "done",
        assigneeAccountId: "123",
        assigneeName: "Alice",
        epicKey: null,
        epicName: null,
        linkedPRs: [
          {
            number: 1,
            title: "PROJ-1 foo",
            repo_full_name: "org/repo",
            html_url: "",
            state: "open",
            checks_status: null,
            author: "alice",
            createdAt: null,
            mergedAt: null,
            reviewState: null,
            waitingReview: false,
          },
        ],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-2",
        summary: "bar",
        status: "Done",
        statusCategory: "done",
        assigneeAccountId: "456",
        assigneeName: "Bob",
        epicKey: null,
        epicName: null,
        linkedPRs: [
          {
            number: 2,
            title: "PROJ-2 bar",
            repo_full_name: "org/repo",
            html_url: "",
            state: "merged",
            checks_status: null,
            author: "bob",
            createdAt: null,
            mergedAt: "2026-06-29T12:00:00Z",
            reviewState: null,
            waitingReview: false,
          },
        ],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-3",
        summary: "baz",
        status: "Done",
        statusCategory: "done",
        assigneeAccountId: "789",
        assigneeName: "Charlie",
        epicKey: null,
        epicName: null,
        linkedPRs: [],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
    ];
    const result = computeHygiene(issues, [], sprintKeys);
    expect(result.doneNoMerged).toEqual([
      { kind: "issue", key: "PROJ-1" },
      { kind: "issue", key: "PROJ-3" },
    ]);
  });

  it("handles edge cases: done issue with zero PRs", () => {
    const issues: EnrichedIssue[] = [
      {
        key: "PROJ-5",
        summary: "no PR at all",
        status: "Done",
        statusCategory: "done",
        assigneeAccountId: "999",
        assigneeName: "Dave",
        epicKey: null,
        epicName: null,
        linkedPRs: [],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
    ];
    const result = computeHygiene(issues, [], sprintKeys);
    expect(result.doneNoMerged).toEqual([{ kind: "issue", key: "PROJ-5" }]);
  });

  it("computes all hygiene buckets together", () => {
    const prs: RawPR[] = [
      {
        number: 1,
        title: "PROJ-1 foo",
        repo_full_name: "org/repo1",
        html_url: "",
        state: "open",
        checks_status: null,
        author: "alice",
        created_at: "2026-07-01T10:00:00Z",
      },
      {
        number: 2,
        title: "no ticket",
        repo_full_name: "org/repo2",
        html_url: "",
        state: "open",
        checks_status: null,
        author: "bob",
        created_at: "2026-07-01T11:00:00Z",
      },
    ];
    const issues: EnrichedIssue[] = [
      {
        key: "PROJ-1",
        summary: "in-progress no PR",
        status: "In Progress",
        statusCategory: "indeterminate",
        assigneeAccountId: "123",
        assigneeName: "Alice",
        epicKey: null,
        epicName: null,
        linkedPRs: [],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: true,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-2",
        summary: "merged but not done",
        status: "In Progress",
        statusCategory: "indeterminate",
        assigneeAccountId: "456",
        assigneeName: "Bob",
        epicKey: null,
        epicName: null,
        linkedPRs: [
          {
            number: 10,
            title: "PROJ-2 merged",
            repo_full_name: "org/repo3",
            html_url: "",
            state: "merged",
            checks_status: null,
            author: "bob",
            createdAt: null,
            mergedAt: "2026-06-30T12:00:00Z",
            reviewState: null,
            waitingReview: false,
          },
        ],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
      {
        key: "PROJ-3",
        summary: "done but PR not merged",
        status: "Done",
        statusCategory: "done",
        assigneeAccountId: "789",
        assigneeName: "Charlie",
        epicKey: null,
        epicName: null,
        linkedPRs: [
          {
            number: 11,
            title: "PROJ-3 open",
            repo_full_name: "org/repo4",
            html_url: "",
            state: "open",
            checks_status: null,
            author: "charlie",
            createdAt: null,
            mergedAt: null,
            reviewState: null,
            waitingReview: false,
          },
        ],
        createdAt: null,
        updatedAt: null,
        dueDate: null,
        storyPoints: null,
        ageDays: 0,
        daysSinceUpdate: 0,
        flags: {
          unassigned: false,
          noEpic: false,
          stale: false,
          addedAfterStart: false,
          dueSoon: false,
          prFailingCI: false,
          prWaitingReview: false,
          inProgressNoPR: false,
        },
        risk: { score: 0, level: "normal", reasons: [] },
      },
    ];

    const result = computeHygiene(issues, prs, sprintKeys);

    expect(result.prNoJira).toEqual([{ kind: "pr", repo: "org/repo2", number: 2 }]);
    expect(result.jiraNoPR).toEqual([{ kind: "issue", key: "PROJ-1" }]);
    expect(result.mergedNotDone).toEqual([{ kind: "issue", key: "PROJ-2" }]);
    expect(result.doneNoMerged).toEqual([{ kind: "issue", key: "PROJ-3" }]);
  });
});
