/**
 * A complete, realistic TeamDashboard for building/testing cockpit components
 * in isolation before the enriched backend lands. Keep it valid against the
 * contract in src/types/teams.ts.
 */
import type { TeamDashboard } from "../../../types/teams";

export const dashboardFixture: TeamDashboard = {
  team: { id: 1, name: "Platform", board: { id: 42, name: "PLAT board" } },
  sprint: {
    id: 1001,
    name: "Sprint 24",
    state: "active",
    startDate: "2026-06-26T00:00:00.000Z",
    endDate: "2026-07-10T00:00:00.000Z",
    goal: "Ship the sprint cockpit",
  },
  sprints: [
    {
      id: 1001,
      name: "Sprint 24",
      state: "active",
      startDate: "2026-06-26T00:00:00.000Z",
      endDate: "2026-07-10T00:00:00.000Z",
    },
    {
      id: 1000,
      name: "Sprint 23",
      state: "closed",
      startDate: "2026-06-12T00:00:00.000Z",
      endDate: "2026-06-26T00:00:00.000Z",
    },
  ],
  epics: [
    {
      key: "PLAT-100",
      name: "Cockpit",
      total: 8,
      done: 3,
      stalled: 2,
      issueKeys: ["PLAT-101", "PLAT-102"],
    },
    {
      key: "PLAT-200",
      name: "Auth revamp",
      total: 5,
      done: 4,
      stalled: 0,
      issueKeys: ["PLAT-201"],
    },
    { key: null, name: "No epic", total: 3, done: 0, stalled: 1, issueKeys: ["PLAT-301"] },
  ],
  issues: [
    {
      key: "PLAT-101",
      summary: "Sprint health strip",
      status: "In Progress",
      statusCategory: "indeterminate",
      assigneeAccountId: "u1",
      assigneeName: "Tashfia",
      epicKey: "PLAT-100",
      epicName: "Cockpit",
      linkedPRs: [
        {
          number: 12,
          title: "PLAT-101 health strip",
          repo_full_name: "acme/web",
          html_url: "https://github.com/acme/web/pull/12",
          state: "open",
          checks_status: "FAILURE",
          author: "tashfia",
          createdAt: "2026-06-30T00:00:00.000Z",
          mergedAt: null,
          reviewState: "REVIEW_REQUIRED",
          waitingReview: true,
        },
      ],
      createdAt: "2026-06-27T00:00:00.000Z",
      updatedAt: "2026-06-28T00:00:00.000Z",
      dueDate: null,
      storyPoints: 3,
      ageDays: 5,
      daysSinceUpdate: 4,
      flags: {
        unassigned: false,
        noEpic: false,
        stale: true,
        addedAfterStart: true,
        dueSoon: false,
        prFailingCI: true,
        prWaitingReview: true,
        inProgressNoPR: false,
      },
      risk: {
        score: 7,
        level: "high",
        reasons: ["stale", "PR failing CI", "PR waiting review", "added after start"],
      },
    },
    {
      key: "PLAT-201",
      summary: "Token refresh",
      status: "Done",
      statusCategory: "done",
      assigneeAccountId: "u2",
      assigneeName: "Nadman",
      epicKey: "PLAT-200",
      epicName: "Auth revamp",
      linkedPRs: [],
      createdAt: "2026-06-20T00:00:00.000Z",
      updatedAt: "2026-07-01T00:00:00.000Z",
      dueDate: null,
      storyPoints: 5,
      ageDays: 12,
      daysSinceUpdate: 1,
      flags: {
        unassigned: false,
        noEpic: false,
        stale: false,
        addedAfterStart: false,
        dueSoon: false,
        prFailingCI: false,
        prWaitingReview: false,
        inProgressNoPR: false,
      },
      risk: { score: 0, level: "normal", reasons: [] },
    },
    {
      key: "PLAT-301",
      summary: "Unassigned cleanup",
      status: "To Do",
      statusCategory: "new",
      assigneeAccountId: null,
      assigneeName: null,
      epicKey: null,
      epicName: null,
      linkedPRs: [],
      createdAt: "2026-06-26T00:00:00.000Z",
      updatedAt: "2026-06-26T00:00:00.000Z",
      dueDate: "2026-07-03T00:00:00.000Z",
      storyPoints: null,
      ageDays: 6,
      daysSinceUpdate: 6,
      flags: {
        unassigned: true,
        noEpic: true,
        stale: false,
        addedAfterStart: false,
        dueSoon: true,
        prFailingCI: false,
        prWaitingReview: false,
        inProgressNoPR: false,
      },
      risk: { score: 3, level: "attention", reasons: ["no assignee", "no epic", "due soon"] },
    },
  ],
  workload: [
    {
      accountId: "u1",
      displayName: "Tashfia",
      githubUsername: "tashfia",
      ticketCount: 7,
      prCount: 4,
      byStatus: { new: 1, indeterminate: 3, inReview: 1, done: 2 },
      wip: 4,
      doneCount: 2,
      stalledCount: 2,
      avgDaysSinceUpdate: 2.1,
      stalest: { kind: "issue", key: "PLAT-101" },
      prOpen: 3,
      prReviewing: 1,
      prMerged: 1,
      riskLevel: "high",
      sp: 12,
      doneSP: 3,
    },
    {
      accountId: "u2",
      displayName: "Nadman",
      githubUsername: "nadman",
      ticketCount: 5,
      prCount: 2,
      byStatus: { new: 1, indeterminate: 1, inReview: 0, done: 3 },
      wip: 1,
      doneCount: 3,
      stalledCount: 0,
      avgDaysSinceUpdate: 0.8,
      stalest: null,
      prOpen: 1,
      prReviewing: 0,
      prMerged: 1,
      riskLevel: "normal",
      sp: 10,
      doneSP: 6,
    },
  ],
  progress: { total: 12, new: 3, indeterminate: 4, inReview: 1, done: 4 },
  offBoardPRs: [
    {
      number: 88,
      title: "hotfix: logging",
      repo_full_name: "acme/web",
      html_url: "https://github.com/acme/web/pull/88",
      author: "nadman",
      state: "open",
      ticketKey: null,
      ticketProject: null,
    },
  ],
  counts: { sprintIssues: 12, epics: 3, offBoardPRs: 1 },
  pace: {
    dayOfSprint: 6,
    sprintLength: 14,
    elapsedPct: 0.43,
    totalCount: 12,
    doneCount: 4,
    remainingCount: 8,
    donePct: 0.33,
    behindPace: true,
    committedSP: 34,
    doneSP: 12,
  },
  scope: { addedCount: 2, addedSP: 5 },
  needsAttention: {
    stale: [{ kind: "issue", key: "PLAT-101" }],
    waitingReview: [{ kind: "pr", repo: "acme/web", number: 12 }],
    failingCI: [{ kind: "pr", repo: "acme/web", number: 12 }],
    noLinkedPR: [],
    offBoard: [{ kind: "pr", repo: "acme/web", number: 88 }],
    scopeCreep: [{ kind: "issue", key: "PLAT-101" }],
    unassigned: [{ kind: "issue", key: "PLAT-301" }],
    noEpic: [{ kind: "issue", key: "PLAT-301" }],
  },
  loadBalance: { max: 7, min: 5, imbalance: 2 },
  prFlow: {
    open: 4,
    merged: 2,
    avgFirstReviewH: 18.5,
    avgAgeDays: 2.4,
    failingChecks: 1,
    noJira: 1,
    jiraNoPR: 1,
  },
  hygiene: {
    prNoJira: [{ kind: "pr", repo: "acme/web", number: 88 }],
    jiraNoPR: [{ kind: "issue", key: "PLAT-101" }],
    mergedNotDone: [],
    doneNoMerged: [{ kind: "issue", key: "PLAT-201" }],
  },
  burnup: {
    trackingSince: "2026-06-28",
    points: [
      { date: "2026-06-28", doneCount: 1, totalCount: 12, ideal: 2 },
      { date: "2026-06-30", doneCount: 2, totalCount: 12, ideal: 4 },
      { date: "2026-07-02", doneCount: 4, totalCount: 12, ideal: 6 },
    ],
  },
  insights: [
    {
      key: "behind-pace",
      severity: "warn",
      title: "Behind Pace",
      detail: "43% elapsed, 33% of tickets done.",
    },
    {
      key: "stale-work",
      severity: "critical",
      title: "Stale Work",
      detail: "1 ticket has had no movement > 2 days.",
    },
    {
      key: "review-bottleneck",
      severity: "warn",
      title: "Review Bottleneck",
      detail: "1 PR waiting for review > 24h.",
    },
  ],
  errors: [],
};

export default dashboardFixture;
