name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release-mac:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install
      - run: yarn dist:mac

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.dmg

  release-win:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn install
      - run: yarn dist:win

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.exe
